# Generated by Django 4.2 on 2023-11-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eskolar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
