# Generated by Django 4.2 on 2023-11-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eskolar', '0002_userrole_phone_number_userrole_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
