# Generated by Django 4.2.5 on 2023-10-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eskolar', '0002_userrole_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formname', models.CharField(max_length=50)),
                ('effectivitydate', models.DateTimeField()),
                ('form_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=8)),
            ],
        ),
    ]
