# Generated by Django 4.2 on 2023-11-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eskolar', '0003_userrole_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
