# Generated by Django 4.2 on 2023-11-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eskolar', '0004_alter_userrole_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='course',
            field=models.CharField(choices=[('admin', 'admin'), ('director', 'director'), ('head', 'head'), ('staff', 'staff')], default='student', max_length=30),
        ),
        migrations.AddField(
            model_name='userrole',
            name='student_id',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='year_level',
            field=models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], default='student', max_length=30),
        ),
    ]
