# Generated by Django 4.2 on 2023-11-28 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eskolar', '0004_form_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='applicant',
        ),
    ]
