# Generated by Django 4.2 on 2023-12-01 13:00

from django.db import migrations


def transfer_data(apps, schema_editor):
    AdminUserRole = apps.get_model('eskolar', 'AdminUserRole')
    UserRole = apps.get_model('eskolar', 'UserRole')

    # Transfer data from AdminUserRole to UserRole
    for admin_user in AdminUserRole.objects.all():
        user_data = {
            'email': admin_user.email,
            'first_name': admin_user.first_name,
            'last_name': admin_user.last_name,
            'password': admin_user.password,
            'role': admin_user.role,
        }
        user_role = UserRole(**user_data)
        user_role.save()

        # Optionally, you can delete the AdminUserRole instance
        admin_user.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('eskolar', '0005_remove_form_applicant'),
    ]

    operations = [
        migrations.RunPython(transfer_data),    
    ]
