# Generated by Django 4.2.7 on 2023-12-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eskolar', '0008_alter_userrole_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipsponsor',
            name='contact_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
