# Generated by Django 4.2.7 on 2023-12-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eskolar', '0009_alter_scholarshipsponsor_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='effectivitydate',
            field=models.DateField(),
        ),
    ]
